import {
  imageUrlWomen,
  imageUrlMen,
  gadgetUrl,
  homeFurnishUrls,
} from "./ImageUrls";

export const allProducts = [
  {
    id: "1",
    image: imageUrlWomen[0],
    title: "Anouk",
    subtitle: "Women Yellow & White Printed Kurta with Palazzos",
    stars: 4,
    rating: 150,
    oldPrice: 1799,
    newPrice: 791,
  },
  {
    id: "2",
    image: imageUrlWomen[1],
    title: "Varanga",
    subtitle: "Women Mauve & White Bandhani Printed Pure Cotton Kurta",
    stars: 4,
    rating: 197,
    oldPrice: 2799,
    newPrice: 699,
  },
  {
    id: "3",
    image: imageUrlWomen[2],
    title: "ForeEver 21",
    subtitle: "Blue & White Floral Print Ruched Styled Back Top",
    stars: 3,
    rating: 127,
    oldPrice: 1699,
    newPrice: 529,
  },
  {
    id: "4",
    image: imageUrlWomen[3],
    title: "Marks & Spencer",
    subtitle: "Women Red & White Pure Cotton Solid Pyjamas Set",
    stars: 4,
    rating: 273,
    oldPrice: 1499,
    newPrice: 999,
  },
  {
    id: "5",
    image: imageUrlMen[0],
    title: "HRX",
    subtitle: "Men Yellow Printed Cotton Pure Cotton T-shirt",
    stars: 4,
    rating: 192,
    oldPrice: 699,
    newPrice: 349,
  },
  {
    id: "6",
    image: imageUrlMen[1],
    title: "Roadster",
    subtitle: "Men Maroon & Olive Green Regular Fit Shirt",
    stars: 4,
    rating: 168,
    oldPrice: 1899,
    newPrice: 1044,
  },
  {
    id: "7",
    image: imageUrlMen[2],
    title: "ForeEver 21",
    subtitle: "Men Blue Regular Fit Faded Casual Shirt",
    stars: 5,
    rating: 327,
    oldPrice: 1799,
    newPrice: 809,
  },
  {
    id: "8",
    image: imageUrlMen[3],
    title: "Levi",
    subtitle: "Men Navy Blue Skinny Fit Stretchable Jeans",
    stars: 3,
    rating: 117,
    oldPrice: 1599,
    newPrice: 679,
  },
  {
    id: "9",
    image: gadgetUrl[0],
    title: "Apple",
    subtitle: "White 2nd Gen AirPods with Charging Case",
    stars: 5,
    rating: 492,
    oldPrice: 14900,
    newPrice: 13900,
  },
  {
    id: "10",
    image: gadgetUrl[1],
    title: "Apple",
    subtitle: "Unisex Black Series 3 GPS Smart Watch",
    stars: 4,
    rating: 172,
    oldPrice: 20900,
    newPrice: 18900,
  },
  {
    id: "11",
    image: gadgetUrl[2],
    title: "OnePlus",
    subtitle: "Bullets Wireless Z Bass Edition Earphones",
    stars: 3,
    rating: 203,
    oldPrice: 2190,
    newPrice: 1999,
  },
  {
    id: "12",
    image: gadgetUrl[3],
    title: "JBL",
    subtitle: "Unisex Portable IP67 Water & Dustproof Bluetooth Speaker",
    stars: 5,
    rating: 20,
    oldPrice: 3999,
    newPrice: 3199,
  },
  {
    id: "13",
    image: homeFurnishUrls[0],
    title: "Home Affairs",
    subtitle: "Green & White Bedsheet with 2 Pillow Covers",
    stars: 4,
    rating: 83,
    oldPrice: 1799,
    newPrice: 799,
  },
  {
    id: "14",
    image: homeFurnishUrls[1],
    title: "Aura",
    subtitle: "Pink & Orange Cotton Bedsheet with 2 Pillow Covers",
    stars: 2,
    rating: 117,
    oldPrice: 2199,
    newPrice: 769,
  },
  {
    id: "15",
    image: homeFurnishUrls[2],
    title: "A Homes Grace",
    subtitle: "Pink & White Heavy Winter Double Bed Quilt",
    stars: 4,
    rating: 147,
    oldPrice: 4500,
    newPrice: 3150,
  },
  {
    id: "16",
    image: homeFurnishUrls[3],
    title: "Home Sizzler",
    subtitle: "Yellow Cartoon Character printed Bedsheet",
    stars: 3,
    rating: 47,
    oldPrice: 1199,
    newPrice: 419,
  },
  {
    id: "17",
    image:
      "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Moto G Play 2023",
    subtitle: "3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
    stars: 4.1,
    rating: 2754,
    oldPrice: 16999,
    newPrice: 8299,
  },
  {
    id: "18",
    image:
      "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A15 5G",
    subtitle: "128GB Unlocked Android Smartphone, AMOLED Display",
    stars: 4.1,
    rating: 327,
    oldPrice: 19999,
    newPrice: 16999,
  },
  {
    id: "19",
    image:
      "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A03s",
    subtitle: "Total by Verizon, 32GB, Black - Prepaid Smartphone (Locked)",
    stars: 4,
    rating: 162,
    oldPrice: 5999,
    newPrice: 4299,
  },
  {
    id: "20",
    image:
      "https://m.media-amazon.com/images/I/51m744UUjYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A25 5G",
    subtitle: "128GB 6GB RAM, Dual SIM, Factory Unlocked GSM",
    stars: 4.1,
    rating: 113,
    oldPrice: 19499,
    newPrice: 15199,
  },
  {
    id: "21",
    image:
      "https://m.media-amazon.com/images/I/510Fpe16MoL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Apple iPhone 11",
    subtitle: "64GB, (PRODUCT)RED - Fully Unlocked (Renewed)",
    stars: 4.2,
    rating: 51176,
    oldPrice: 22999,
    newPrice: 17699,
  },
  {
    id: "22",
    image:
      "https://m.media-amazon.com/images/I/71lw4ZWUfYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A35 5G",
    subtitle: "128GB Unlocked Android Smartphone, Advanced Camera",
    stars: 4.1,
    rating: 53,
    oldPrice: 39999,
    newPrice: 29999,
  },
  {
    id: "23",
    image:
      "https://m.media-amazon.com/images/I/61jYjeuNUnL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S21 5G",
    subtitle: "US Version, 128GB, Phantom Gray - Unlocked (Renewed)",
    stars: 3.9,
    rating: 5769,
    oldPrice: 37999,
    newPrice: 15999,
  },
  {
    id: "24",
    image:
      "https://m.media-amazon.com/images/I/51m45B3Yy+L._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A03s",
    subtitle: "AT&T GSM Unlocked Android Smartphone, 32GB",
    stars: 3.9,
    rating: 409,
    oldPrice: 8714,
    newPrice: 6184,
  },
  {
    id: "25",
    image:
      "https://m.media-amazon.com/images/I/718+xprSIBL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Total by Verizon TCL 30 Z",
    subtitle: "32GB, Black - Prepaid Smartphone (Locked)",
    stars: 3.9,
    rating: 28,
    oldPrice: 4999,
    newPrice: 3299,
  },
  {
    id: "26",
    image:
      "https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A04e",
    subtitle: "Dual SIM 32GB, 6.5'' GSM Unlocked, International Version-Black",
    stars: 3.8,
    rating: 547,
    oldPrice: 9901,
    newPrice: 6499,
  },
  {
    id: "27",
    image:
      "https://m.media-amazon.com/images/I/71pGGUaxezL._AC_UY654_FMwebp_QL65_.jpg",
    title: "TracFone Motorola",
    subtitle: "32GB, Black - Prepaid Smartphone (Locked)",
    stars: 4,
    rating: 180,
    oldPrice: 4999,
    newPrice: 3752,
  },
  {
    id: "28",
    image:
      "https://m.media-amazon.com/images/I/716UvwH-NvL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S24",
    subtitle: "256GB AI Smartphone, Unlocked Android, 50MP Camera",
    stars: 4.5,
    rating: 1582,
    oldPrice: 58999,
    newPrice: 48999,
  },
  {
    id: "29",
    image:
      "https://m.media-amazon.com/images/I/610brW3Dn7L._AC_UY654_FMwebp_QL65_.jpg",
    title: "AT&T 210 Basic Trimline",
    subtitle: "Wall-Mountable, No AC Power Required",
    stars: 4.2,
    rating: 19399,
    oldPrice: 1795,
    newPrice: 1295,
  },
  {
    id: "30",
    image:
      "https://m.media-amazon.com/images/I/21f9A+OzosL._AC_UY365_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A05s",
    subtitle: "128GB 4GB RAM, Dual SIM, Factory Unlocked GSM",
    stars: 4,
    rating: 20,
    oldPrice: 13499,
    newPrice: 9999,
  },
  {
    id: "31",
    image:
      "https://m.media-amazon.com/images/I/81k6vcykYYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Panasonic Compact",
    subtitle: "DECT 6.0, 1.6'' Amber LCD, Call Block, Caller ID",
    stars: 4.2,
    rating: 5295,
    oldPrice: 2999,
    newPrice: 1999,
  },
];

export const womenClothing = [
  {
    id: "1",
    image: imageUrlWomen[0],
    title: "Anouk",
    subtitle: "Women Yellow & White Printed Kurta with Palazzos",
    stars: 4,
    rating: 150,
    oldPrice: 1799,
    newPrice: 791,
  },
  {
    id: "2",
    image: imageUrlWomen[1],
    title: "Varanga",
    subtitle: "Women Mauve & White Bandhani Printed Pure Cotton Kurta",
    stars: 4,
    rating: 197,
    oldPrice: 2799,
    newPrice: 699,
  },
  {
    id: "3",
    image: imageUrlWomen[2],
    title: "ForeEver 21",
    subtitle: "Blue & White Floral Print Ruched Styled Back Top",
    stars: 3,
    rating: 127,
    oldPrice: 1699,
    newPrice: 529,
  },
  {
    id: "4",
    image: imageUrlWomen[3],
    title: "Marks & Spencer",
    subtitle: "Women Red & White Pure Cotton Solid Pyjamas Set",
    stars: 4,
    rating: 273,
    oldPrice: 1499,
    newPrice: 999,
  },
];

export const menClothing = [
  {
    id: "5",
    image: imageUrlMen[0],
    title: "HRX",
    subtitle: "Men Yellow Printed Cotton Pure Cotton T-shirt",
    stars: 4,
    rating: 192,
    oldPrice: 699,
    newPrice: 349,
  },
  {
    id: "6",
    image: imageUrlMen[1],
    title: "Roadster",
    subtitle: "Men Maroon & Olive Green Regular Fit Shirt",
    stars: 4,
    rating: 168,
    oldPrice: 1899,
    newPrice: 1044,
  },
  {
    id: "7",
    image: imageUrlMen[2],
    title: "ForeEver 21",
    subtitle: "Men Blue Regular Fit Faded Casual Shirt",
    stars: 5,
    rating: 327,
    oldPrice: 1799,
    newPrice: 809,
  },
  {
    id: "8",
    image: imageUrlMen[3],
    title: "Levi",
    subtitle: "Men Navy Blue Skinny Fit Stretchable Jeans",
    stars: 3,
    rating: 117,
    oldPrice: 1599,
    newPrice: 679,
  },
];

export const gadgets = [
  {
    id: "9",
    image: gadgetUrl[0],
    title: "Apple",
    subtitle: "White 2nd Gen AirPods with Charging Case",
    stars: 5,
    rating: 492,
    oldPrice: 14900,
    newPrice: 13900,
  },
  {
    id: "10",
    image: gadgetUrl[1],
    title: "Apple",
    subtitle: "Unisex Black Series 3 GPS Smart Watch",
    stars: 4,
    rating: 172,
    oldPrice: 20900,
    newPrice: 18900,
  },
  {
    id: "11",
    image: gadgetUrl[2],
    title: "OnePlus",
    subtitle: "Bullets Wireless Z Bass Edition Earphones",
    stars: 3,
    rating: 203,
    oldPrice: 2190,
    newPrice: 1999,
  },
  {
    id: "12",
    image: gadgetUrl[3],
    title: "JBL",
    subtitle: "Unisex Portable IP67 Water & Dustproof Bluetooth Speaker",
    stars: 5,
    rating: 20,
    oldPrice: 3999,
    newPrice: 3199,
  },
];

export const homeFurnish = [
  {
    id: "13",
    image: homeFurnishUrls[0],
    title: "Home Affairs",
    subtitle: "Green & White Bedsheet with 2 Pillow Covers",
    stars: 4,
    rating: 83,
    oldPrice: 1799,
    newPrice: 799,
  },
  {
    id: "14",
    image: homeFurnishUrls[1],
    title: "Aura",
    subtitle: "Pink & Orange Cotton Bedsheet with 2 Pillow Covers",
    stars: 2,
    rating: 117,
    oldPrice: 2199,
    newPrice: 769,
  },
  {
    id: "15",
    image: homeFurnishUrls[2],
    title: "A Homes Grace",
    subtitle: "Pink & White Heavy Winter Double Bed Quilt",
    stars: 4,
    rating: 147,
    oldPrice: 4500,
    newPrice: 3150,
  },
  {
    id: "16",
    image: homeFurnishUrls[3],
    title: "Home Sizzler",
    subtitle: "Yellow Cartoon Character printed Bedsheet",
    stars: 3,
    rating: 47,
    oldPrice: 1199,
    newPrice: 419,
  },
];

export const smartphones = [
  {
    id: "17",
    image:
      "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Moto G Play 2023",
    subtitle: "3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
    stars: 4.1,
    rating: 2754,
    oldPrice: 16999,
    newPrice: 8299,
  },
  {
    id: "18",
    image:
      "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A15 5G",
    subtitle: "128GB Unlocked Android Smartphone, AMOLED Display",
    stars: 4.1,
    rating: 327,
    oldPrice: 19999,
    newPrice: 16999,
  },
  {
    id: "19",
    image:
      "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A03s",
    subtitle: "Total by Verizon, 32GB, Black - Prepaid Smartphone (Locked)",
    stars: 4,
    rating: 162,
    oldPrice: 5999,
    newPrice: 4299,
  },
  {
    id: "20",
    image:
      "https://m.media-amazon.com/images/I/51m744UUjYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A25 5G",
    subtitle: "128GB 6GB RAM, Dual SIM, Factory Unlocked GSM",
    stars: 4.1,
    rating: 113,
    oldPrice: 19499,
    newPrice: 15199,
  },
  {
    id: "21",
    image:
      "https://m.media-amazon.com/images/I/510Fpe16MoL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Apple iPhone 11",
    subtitle: "64GB, (PRODUCT)RED - Fully Unlocked (Renewed)",
    stars: 4.2,
    rating: 51176,
    oldPrice: 22999,
    newPrice: 17699,
  },
  {
    id: "22",
    image:
      "https://m.media-amazon.com/images/I/71lw4ZWUfYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A35 5G",
    subtitle: "128GB Unlocked Android Smartphone, Advanced Camera",
    stars: 4.1,
    rating: 53,
    oldPrice: 39999,
    newPrice: 29999,
  },
  {
    id: "23",
    image:
      "https://m.media-amazon.com/images/I/61jYjeuNUnL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S21 5G",
    subtitle: "US Version, 128GB, Phantom Gray - Unlocked (Renewed)",
    stars: 3.9,
    rating: 5769,
    oldPrice: 37999,
    newPrice: 15999,
  },
  {
    id: "24",
    image:
      "https://m.media-amazon.com/images/I/51m45B3Yy+L._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A03s",
    subtitle: "AT&T GSM Unlocked Android Smartphone, 32GB",
    stars: 3.9,
    rating: 409,
    oldPrice: 8714,
    newPrice: 6184,
  },
  {
    id: "25",
    image:
      "https://m.media-amazon.com/images/I/718+xprSIBL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Total by Verizon TCL 30 Z",
    subtitle: "32GB, Black - Prepaid Smartphone (Locked)",
    stars: 3.9,
    rating: 28,
    oldPrice: 4999,
    newPrice: 3299,
  },
  {
    id: "26",
    image:
      "https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A04e",
    subtitle: "Dual SIM 32GB, 6.5'' GSM Unlocked, International Version-Black",
    stars: 3.8,
    rating: 547,
    oldPrice: 9901,
    newPrice: 6499,
  },
  {
    id: "27",
    image:
      "https://m.media-amazon.com/images/I/71pGGUaxezL._AC_UY654_FMwebp_QL65_.jpg",
    title: "TracFone Motorola",
    subtitle: "32GB, Black - Prepaid Smartphone (Locked)",
    stars: 4,
    rating: 180,
    oldPrice: 4999,
    newPrice: 3752,
  },
  {
    id: "28",
    image:
      "https://m.media-amazon.com/images/I/716UvwH-NvL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S24",
    subtitle: "256GB AI Smartphone, Unlocked Android, 50MP Camera",
    stars: 4.5,
    rating: 1582,
    oldPrice: 58999,
    newPrice: 48999,
  },
  {
    id: "29",
    image:
      "https://m.media-amazon.com/images/I/610brW3Dn7L._AC_UY654_FMwebp_QL65_.jpg",
    title: "AT&T 210 Basic Trimline",
    subtitle: "Wall-Mountable, No AC Power Required",
    stars: 4.2,
    rating: 19399,
    oldPrice: 1795,
    newPrice: 1295,
  },
  {
    id: "30",
    image:
      "https://m.media-amazon.com/images/I/21f9A+OzosL._AC_UY365_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy A05s",
    subtitle: "128GB 4GB RAM, Dual SIM, Factory Unlocked GSM",
    stars: 4,
    rating: 20,
    oldPrice: 13499,
    newPrice: 9999,
  },
  {
    id: "31",
    image:
      "https://m.media-amazon.com/images/I/81k6vcykYYL._AC_UY654_FMwebp_QL65_.jpg",
    title: "Panasonic Compact",
    subtitle: "DECT 6.0, 1.6'' Amber LCD, Call Block, Caller ID",
    stars: 4.2,
    rating: 5295,
    oldPrice: 2999,
    newPrice: 1999,
  },
];
